name: cronjob-hello-world 
on: push
  # schedule:
  #   - cron: "1 * * * *"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Date
        uses: date

      - name: Clone repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run python script
        run: python hello.py
