name: secret
on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: execute helloworld-secret.py script 
        env:
          HELLO_WORLD: ${{ secrets.SECRET_MSG }}
          HI: "Hi"
        run: python helloworld-secret.py
          