name: send a mail
on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        run: echo "Hello, World!"

      - name: Send a mail
        if: ${{ always() }} #failure, success ,cancelled
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: harshajsharsh@gmail.com, abcd@gmail.com
          from: Harsha JS